create table if not exists banking_details (bank_id integer not null, account_number varchar(255), account_type varchar(255), bank_name varchar(255), branch_code varchar(255), primary key (bank_id));

create table if not exists  department (id integer not null, code varchar(255), name varchar(255), primary key (id));

create table if not exists  employee (id integer generated by default as identity, name varchar(255), surname varchar(255), fk_bank_id integer, fk_department_id integer, primary key (id));

create table if not exists  employee_project (employee_id integer not null, project_id integer not null);

create table if not exists  project (id integer not null, code varchar(255), name varchar(255), primary key (id));

create sequence banking_details_seq start with 1 increment by 50;

create sequence department_seq start with 1 increment by 50;

create sequence project_seq start with 1 increment by 50;

alter table if exists employee add constraint FKlmgrl3vbe2maccifaquu0pfjf foreign key (fk_bank_id) references banking_details;
alter table if exists employee add constraint FKqtm6mt7fjwg0hf36w0x40hrfp foreign key (fk_department_id) references department;
alter table if exists employee_project add constraint FK4yddvnm7283a40plkcti66wv9 foreign key (project_id) references project;
alter table if exists employee_project add constraint FKb25s5hgggo6k4au4sye7teb3a foreign key (employee_id) references employee;


