create table banking_details (
             bank_id bigint not null,
             account_number varchar(255),
             account_type varchar(255),
             bank_name varchar(255),
             branch_code varchar(255),
             primary key (bank_id));

create table person (
             id integer generated by default as identity,
             name varchar(255),
             surname varchar(255),
             fk_bank_id bigint,
             primary key (id));

create sequence banking_details_seq start with 1 increment by 50
