version: "3.8"
services:
  postgres:
    image: postgres:alpine
    container_name: momentum-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=momentum-postgres-db
    restart: unless-stopped
  app:
    image: momentum/momentum-app
    container_name: momentum-app
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - /home/admin01/dev:/var/tmp
    restart: unless-stopped
    depends_on:
      - postgres
      - kafka
  pgadmin:
    container_name: momemtum-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: wanted.lepota@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "82:80"
volumes:
  postgres-data:

